name:                 Practica04
version:              0.1.0.0
visibility:           public
id:                   Practica04-0.1.0.0-inplace
key:                  Practica04-0.1.0.0-inplace
maintainer:           eduardovar1090@ciencias.unam.mx
author:               EduardoVrP
synopsis:             Practica 4: Algoritmo DPLL
abi:                  inplace
exposed:              True
exposed-modules:      Practica04
import-dirs:
    "/home/slvdrply21/Personal/4to semestre/Logica computacional/practicasLC/LC2026-2-Practica04/dist-newstyle/build/x86_64-linux/ghc-9.6.7/Practica04-0.1.0.0/build"

library-dirs:
    "/home/slvdrply21/Personal/4to semestre/Logica computacional/practicasLC/LC2026-2-Practica04/dist-newstyle/build/x86_64-linux/ghc-9.6.7/Practica04-0.1.0.0/build"

library-dirs-static:
    "/home/slvdrply21/Personal/4to semestre/Logica computacional/practicasLC/LC2026-2-Practica04/dist-newstyle/build/x86_64-linux/ghc-9.6.7/Practica04-0.1.0.0/build"

dynamic-library-dirs:
    "/home/slvdrply21/Personal/4to semestre/Logica computacional/practicasLC/LC2026-2-Practica04/dist-newstyle/build/x86_64-linux/ghc-9.6.7/Practica04-0.1.0.0/build"

data-dir:
    "/home/slvdrply21/Personal/4to semestre/Logica computacional/practicasLC/LC2026-2-Practica04/."

hs-libraries:         HSPractica04-0.1.0.0-inplace
depends:              base-4.18.3.0
haddock-interfaces:
    "/home/slvdrply21/Personal/4to semestre/Logica computacional/practicasLC/LC2026-2-Practica04/dist-newstyle/build/x86_64-linux/ghc-9.6.7/Practica04-0.1.0.0/doc/html/Practica04/Practica04.haddock"

haddock-html:
    "/home/slvdrply21/Personal/4to semestre/Logica computacional/practicasLC/LC2026-2-Practica04/dist-newstyle/build/x86_64-linux/ghc-9.6.7/Practica04-0.1.0.0/doc/html/Practica04"
